baseURL = "https://batasrki.github.io/"
languageCode = "en-us"
title = "(Insightful) Ramblings"
theme = "ananke"
pygmentsCodeFences = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5